### ISSUE TITLE
bootstrap 3 not working 

### ISSUE THREAD

**Issue by athimannil** [bmbrands/theme_bootstrap#142]
Moodle Bootstrap 3 is not appear when apply :( 

seems to be like this when select Bootstrap3 theme. 

![moodle](https://f.cloud.github.com/assets/4364227/2323552/1c5911a0-a3be-11e3-8209-97017252ebfd.png)

Rest of the themes are working fine

**Comment by wkchung** [comment]
I had the same problem and as the above mentioned, I tried to comment out "$csscontent = core_minify::css($csscontent);" and everything's fixed.
Not sure about the compatibility with older versions of browser tho.

**Comment by julianodenner** [comment]
I comment out "$csscontent = core_minify::css($csscontent);" and work for me too.
