### ISSUE TITLE
Shibboleth login page unusable

### ISSUE THREAD

**Issue by mackensen** [bmbrands/theme_bootstrap#285]
Shibboleth has its own page for selecting an IDP. This page doesn't render properly: the drop-down is hidden. This makes it impossible to login normally to the Moodle site. This isn't an issue with Clean.
![bootstrap3-shibboleth](https://cloud.githubusercontent.com/assets/553370/3192825/bada7920-ecea-11e3-8d41-86ab70c70091.png)

**Comment by pexpert9** [comment]
I have Issue Related Moodle Shibboleth configuration and i have questions ...
1.) Is required to installed shibboleth separately .
2.) Moodle provide the shibboleth plugin .. Is it sufficient or not ...
3.) I have two moodle 
    I want to created one moodle to SP and one moodle to IDP
    how can i achieved this.
4.) How to add IDP list in Moodle.
Please provides solutions

**Comment by pexpert9** [comment]
![shibboleth](https://user-images.githubusercontent.com/38654039/40484645-f4432c60-5f79-11e8-92d7-c8e67627a466.png)

Whats the reason behind above error.

**Comment by bmbrands** [comment]
I am not an expert on Shibboleth configurations. Do you have any proof this is a theme issue?

**Comment by pexpert9** [comment]
I have facing Error with Following information ............................

![shibboleth](https://user-images.githubusercontent.com/38654039/40484993-e7b85cb2-5f7a-11e8-8f94-1032cf7b11d5.png)
![1](https://user-images.githubusercontent.com/38654039/40485000-eb0da552-5f7a-11e8-8579-f86efc93e465.png)
![2](https://user-images.githubusercontent.com/38654039/40485004-edbcd1c4-5f7a-11e8-94b2-209f25de4572.png)

**Comment by bmbrands** [comment]
I am sorry but this is not related to the bootstrap theme. Please use Moodle forums for questions like these.
