### ISSUE TITLE
Define rubric page is broken

### ISSUE THREAD

**Issue by mackensen** [bmbrands/theme_bootstrap#346]
On the rubric definition page the text inputs and textareas are supposed to be hidden unless clicked on. They're all displaying by default which makes a mess of the page. Follow these steps to re-create:

1. Create an assignment.
2. Set the grade method to rubric.
3. Submit the assignment.
4. Edit the assignment and choose "Advanced grading"
5. Click on "Define Rubric"
6. Try entering point values for a level.

![define rubics](https://cloud.githubusercontent.com/assets/553370/4815984/7bdc4682-5edb-11e4-8921-0e6d3d925b8e.png)

At first glance a greedy input[type=text] selector might be responsible.

**Comment by bmbrands** [comment]
I pushed a fix for this

**Comment by bmbrands** [comment]
Thanks for reporting the issue!
