### ISSUE TITLE
Improve display on 'define rubric' screen (fonts too large)

### ISSUE THREAD

**Issue by thepurpleblob** [bmbrands/theme_bootstrap#354]
The font choices on the define rubric page are poor rendering the screen almost unusable. Compared with the (say) Clean theme the fonts are very large making the page unwieldy and prone to being truncated. 

Here's an example...

![screen shot 2015-01-07 at 11 04 31](https://cloud.githubusercontent.com/assets/664139/5644575/00bfc30c-965d-11e4-907c-a23fb2be1ce7.png)

**Comment by bmbrands** [comment]
Sorry for the late reply.
I am having a hard time trying to create this rubric page. Could you provide the steps you took to create this specific page?

**Comment by bmbrands** [comment]
nevermind found it :)

**Comment by bmbrands** [comment]
Thanks for reporting this, I think I fixed it.
