### ISSUE TITLE
plugin version on master branch != plugin version in zip archive ?

### ISSUE THREAD

**Issue by pfautrero** [bmbrands/theme_bootstrap#355]
Hi,
I cloned the repo and tried to use it in my local moodle but we have this in the version.php :
  $plugin->version   = 2014022000;

If I download the theme with the zip archive, I can see this :
  $plugin->version   = 2014120803;

Which branch should we use to get the latest version ?

Thanks

**Comment by bmbrands** [comment]
Thanks for reporting this. I have updated the version number here on Git. Both now use version number
2014120803

**Comment by pfautrero** [comment]
great, it works. Thanks.
