### ISSUE TITLE
2.9 New Message pop up window close button does not work

### ISSUE THREAD

**Issue by emmarichardson** [bmbrands/theme_bootstrap#361]
On 2.9, if you open the newly featured Send Message popup, you cannot close it with the Close button.  Everything else appears to work (send button/link to conversation).

**Comment by bmbrands** [comment]
Thanks for reporting this. For Moodle 2.9 we are still working on having everything updated. There are still a few more broken features.

**Comment by emmarichardson** [comment]
Good deal - anxiously awaiting it!  Would hate to have to switch themes right now!

Emma Richardson
Distance Learning Coordinator
Direct: 719-650-3037
Desktop Video: https://ecboces.zoom.us/j/7196503037<https://ecboces.zoom.us/my/emmar>




On May 17, 2015 at 3:19:26 AM, Bas Brands (notifications@github.com<mailto:notifications@github.com>) wrote:

Thanks for reporting this. For Moodle 2.9 we are still working on having everything updated. There are still a few more broken features.

**Comment by gjb2048** [comment]
I have a fix for this and will do a pull request presently.
