### ISSUE TITLE
Grunt LESS -> CSS background: color gives -> background:0 0 in css.

### ISSUE THREAD

**Issue by gjb2048** [bmbrands/theme_bootstrap#369]
Hi Bas,

More of an advisory check:

I noticed that when using the grunt LESS compiler with Essential that any attribute of 'background' with only the colour specified results in 'background:0 0' in the 'minimised' CSS only. Does not happen otherwise.  Need to change instances to 'background-color' to fix.

Cheers,

Gareth

**Comment by gjb2048** [comment]
Note: Happens with 'grunt-contrib-cssmin' not 'grunt-contrib-less'.

**Comment by bmbrands** [comment]
Oh thanks for letting me know. I am not sure about the official rules but I always regarded 'background: #color' being invalid css. In any case, good to know! thanks

**Comment by gjb2048** [comment]
Hi Bas,

Oh I mean that legitimate css like 'background: white' / 'background: #fff' when put through cssmin gives 'background:0 0'.

Gareth
