### ISSUE TITLE
missing icon when adding bootstrap.min.css

### ISSUE THREAD

**Issue by meobien** [bmbrands/theme_bootstrap#370]
Hi all,

I have a problem of bootstrap.min.css. When I add it to my code, the show/hide icon topic is hidden.
Attached file is the error. Please help me to fix it. Thank you

![error](https://cloud.githubusercontent.com/assets/12965437/8251524/756d2a58-16a7-11e5-9dd9-54c56bba07ef.png)

**Comment by bmbrands** [comment]
Closing this since it is not related to the Moodle bootstrap theme.
You can use your browsers inspector to see what css classes hide the image.
