### ISSUE TITLE
Broken user profile layout...

### ISSUE THREAD

**Issue by gjb2048** [bmbrands/theme_bootstrap#371]
Hi Bas,

I cannot find fault in layout/default.php on this and only happens on the user profile page:

![2015-06-20 11_49_27-course creation groups and enrolment_ personal profile_ another student](https://cloud.githubusercontent.com/assets/1058419/8266975/fa4a1b0a-1742-11e5-8879-c9d64918d76e.jpg)

Block regions are inside 'main', so a missing closing 'div' somewhere caused I suspect by an overridden method.  Cannot replicate the issue in Clean or Shoehorn, so core renderer code correct.

MOODLE_29_STABLE and master branches.

To replicate, find another user and look at their profile.

Cheers,

Gareth

**Comment by bmbrands** [comment]
Oh wow, that looks terrible. I found the issue in /user/view.php 2 starting divs on line 194, 210. Just one closing div on line 231. So this is a core Moodle issue that, for some reason is not seen in bootstrap2 based themes. I will report it on the Moodle tracker.
Thanks for reporting it here :)

**Comment by gjb2048** [comment]
No worries Bas, odd it's fine in other themes, must be a double reciprocal error elsewhere.

**Comment by bmbrands** [comment]
Issue now fix in https://tracker.moodle.org/browse/MDL-50653
