### ISSUE TITLE
Assignment rubrics (still) not displaying correctly - width truncated

### ISSUE THREAD

**Issue by thepurpleblob** [bmbrands/theme_bootstrap#374]
Compare the same rubric, first with the clean theme...

![screenshot 2015-06-22 11 41 33](https://cloud.githubusercontent.com/assets/664139/8280284/d1a38cb2-18d3-11e5-9ac9-797a84ee1a91.png)

...and now with bootstrap...

![screenshot 2015-06-22 11 41 57](https://cloud.githubusercontent.com/assets/664139/8280290/dc0628cc-18d3-11e5-8d48-c3f2032cf537.png)

The rubric is truncated and the auto-hiding of the points edit boxes doesn't work properly (the point box is not hidden).

This with the latest Moodle 2.9+ and  Bootstrap 2015062200

**Comment by bmbrands** [comment]
Thanks for reporting it! I've seen this one before :)

**Comment by thepurpleblob** [comment]
Cool - I know there are some other reports about Rubrics but I wasn't sure they quite covered it :-D

**Comment by bmbrands** [comment]
I think I fixed it in my latest commit! Could you give it a try?

**Comment by gjb2048** [comment]
Hi Bas,

I updated today at https://github.com/bmbrands/theme_bootstrap/commit/0d3e27d16c7195a734cb4aa68c5bd58a94e2b925 - and tried and did not work.  Could not work out the fix though :(.

G

**Comment by bmbrands** [comment]
Oops ! Forgot to push my changes!

**Comment by thepurpleblob** [comment]
Looks good - thanks for the very rapid response :)

I'm asking our Rubrics expert for a second opinion just to be sure!
