### ISSUE TITLE
MOODLE_28_STABLE has 'node_modules' folder.

### ISSUE THREAD

**Issue by gjb2048** [bmbrands/theme_bootstrap#375]
Hi Bas,

I've noticed that the MOODLE_28_STABLE branch contains the 'node_modules' folder: https://github.com/bmbrands/theme_bootstrap/tree/MOODLE_28_STABLE/node_modules - this for me caused a Git Pull warning (lost capture of it).

It also adds 56.5 MB to the size of the theme!

I believe that it should only exist locally and created when a developer uses 'grunt' otherwise for other users, the folder is pointless.

Cheers,

Gareth

**Comment by bmbrands** [comment]
Ah yes your right. I have no idea how that got in there with my .gitignore in place.
All cleaned up now

Thanks!
