### ISSUE TITLE
'Preferences' option missing from user dropdown in 2.9

### ISSUE THREAD

**Issue by thepurpleblob** [bmbrands/theme_bootstrap#378]
The dropdown under the user image at the top right should have things like 'profile', 'messages' etc. 

Added in 2.9 was 'preferences' but this is completely missing when using the bootstrap theme. This is a bit of a disaster frankly.

**Comment by bmbrands** [comment]
I agree. That really needed an update. I have just pushed a change for this on the master repository. It would be great if you could give it a try!

**Comment by thepurpleblob** [comment]
Yep - the option is there now. 

For some reason it no longer positions properly in the header in my child theme so I'll need to investigate that :)

Thanks for the fix.

**Comment by bmbrands** [comment]
Ah yes, the structure of the layout/default.php file has changed a bit. So if you copy over that part it should be okay!
