### ISSUE TITLE
PDF annotation broken (in 2.9 at least)...

### ISSUE THREAD

**Issue by thepurpleblob** [bmbrands/theme_bootstrap#379]
The editable text boxes appear far too big when annotating PDFs in Assignment. It's fine in core themes.

Example.... first in clean theme:

<img width="851" alt="screen shot 2015-08-05 at 09 19 17" src="https://cloud.githubusercontent.com/assets/664139/9081310/16ca606c-3b53-11e5-8d17-7da1374bb4ed.png">

...and now in Bootstrap...

<img width="840" alt="screen shot 2015-08-05 at 09 17 52" src="https://cloud.githubusercontent.com/assets/664139/9081287/ecbd8a1a-3b52-11e5-9920-ac95bfdefe05.png">

**Comment by bmbrands** [comment]
Thanks for reporting this and thanks for adding those screenshots!

mysterious issue but everything can be fixed :) . Will look into it

**Comment by thepurpleblob** [comment]
Just wondering if you got anywhere with this? I had a look and am deeply confused. The javascript sets the height of the box so something must be making it calculate it "wrongly". It doesn't help that YUI is something of an arcane mystery to me :)

**Comment by bmbrands** [comment]
No yet no. I have been trying to find where this goes wrong. Changing the JS is not an option so there has to be some theme css that is causing this. Something that affects all css like the box-border stuff. I just haven't found which bit it is yet.

**Comment by thepurpleblob** [comment]
I don't know if you noticed but there's also a little dialogue box (for delete etc) that's supposed to be in the top-right corner of the textarea but has been pushed to a position beneath the box.

**Comment by bmbrands** [comment]
Finally found the issue ! Thanks to Alex Walker who reminded me of this again :+1:
