### ISSUE TITLE
###### are not converted to dividers

### ISSUE THREAD

**Issue by gjb2048** [bmbrands/theme_bootstrap#380]
Hi Bas,

On the custom menu, ##### are not converted into dividers.  As per the instructions for https://tracker.moodle.org/browse/MDL-50533.  You just get '#####' on the menu bar.  The solution is: https://github.com/gjb2048/moodle-theme_essential/blob/925ef042c105336b9f982abf8e21c432e25962b8/renderers/core_renderer.php#L180-L197 - but I've not figured out how to make them show when small screen yet: https://github.com/gjb2048/moodle-theme_essential/issues/529.

Cheers,

Gareth

**Comment by gjb2048** [comment]
i.e:

![2015_08_14_16_09_07_moo29_administration_appearance_themes_theme_settings](https://cloud.githubusercontent.com/assets/1058419/9276971/323e2376-429f-11e5-9238-133bd14bece0.png)

**Comment by bmbrands** [comment]
Okay implemented into this theme too. Thanks for the suggested solution
