### ISSUE TITLE
Assignment rubrics: 'Add level' button is obscured after defining a few levels

### ISSUE THREAD

**Issue by thepurpleblob** [bmbrands/theme_bootstrap#382]
To reproduce...

- Create an assignment
- Switch on advanced grading and select rubrics
- Define the rubric
- You will have one, empty rubric shown. Click 'Add level' a few times

After a few clicks the button vanishes due to the containing <div>'s overflow and size. 

After a quick look the div with selector .gradingform_rubric seems to be the issue. Removing the 'overflow: auto' seems to improve things a little. 

A side note:  My child theme has the navigation on the right and even changing the overflow to visible doesn't help me. The button now vanishes behind the side blocks. This is probably my problem but it seems that the prospective width of this table isn't handled well. I'm unsure where the solution lies.

**Comment by bmbrands** [comment]
I could reproduce this issue. I think the issue here is the UI itself. Just like the gradebook tables can grow very large. The max-width set in the rubrics styles.css of 720 px does ot seem to help either. 

I have removed the max-width for the bootstrap theme, I think that's all i can do here :(
