### ISSUE TITLE
too much space under labels

### ISSUE THREAD

**Issue by thepurpleblob** [bmbrands/theme_bootstrap#383]
Compared to the 'clean' theme, Bootstrap leaves a lot more space underneath a label (in between the label content and the next activity/resource). If the label is being used as a heading (and they often are) the label is far enough away to be dissociated from the following content. 

Compare... clean theme
![screen shot 2015-08-20 at 13 03 05](https://cloud.githubusercontent.com/assets/664139/9382855/198e9f62-473c-11e5-98d0-56260d6fd975.png)

Bootstrap theme...
![screen shot 2015-08-20 at 13 02 49](https://cloud.githubusercontent.com/assets/664139/9382864/26476ce8-473c-11e5-8683-2c12e62c74c9.png)

At a "very" quick glance it seems to be caused by a 15px bottom margin in the .no-overflow selector.

**Comment by bmbrands** [comment]
Yes much better with 1px bottom margin :) Thanks for reporting. 

Achievement unlocked: 
:+1: Number 1 tester !!!
