### ISSUE TITLE
Use of nowrap with weeks section names

### ISSUE THREAD

**Issue by mackensen** [bmbrands/theme_bootstrap#384]
`less/moodle/course.less` sets `white-space: nowrap` for `ul.weeks` > `h3.sectionname`. This is also present in bootstrapbase. Teachers can enter arbitrary section names in both topics and weekly, and we're seeing clipping. I don't understand the rationale for treating weeks differently from `ul.topics`.

**Comment by bmbrands** [comment]
Oops! Sorry for my late reply! 

I am trying to catch up with all the reported issues now.

Thanks very much for reporting this! I agree it makes no sense to have a nowrap for the section names. I have no clue why it was added. Removed it and updated the master branch.
