### ISSUE TITLE
"manage courses" is near unusable when many cateories

### ISSUE THREAD

**Issue by thepurpleblob** [bmbrands/theme_bootstrap#385]
(2.9.1) On a site with a lot of categories and subcategories, the "manages courses and categories" screen is badly formatted in Bootstrap compared to clean. It is actually near unusable (especially on smaller screens).

Bootstrap:
<img width="678" alt="screen shot 2015-08-26 at 10 57 59" src="https://cloud.githubusercontent.com/assets/664139/9490668/643dfc2a-4be1-11e5-9747-3648f4fbafe7.png">

Clean:
<img width="785" alt="screen shot 2015-08-26 at 10 59 01" src="https://cloud.githubusercontent.com/assets/664139/9490678/8262daae-4be1-11e5-8b78-583913097093.png">

**Comment by bmbrands** [comment]
Thanks again for reporting the issues you find!

For this one I think I submitted a fix some time ago, and I can replicate it on my local version. Could you check if you are using the latest commit from the master branch?

**Comment by thepurpleblob** [comment]
Ahh... you're right. I didn't have the correct version on my production box. Oops

It's much improved, however, if I was to be picky (!) I still feel that there is a lot of white space compared to (say) the Clean theme. This page can get *very* busy and as compact a presentation as possible would be beneficial.

**Comment by bmbrands** [comment]
closing for now. I you feel like there needs more work on the course management page let me know!
