### ISSUE TITLE
formslib groups are incorrectly spaced

### ISSUE THREAD

**Issue by thepurpleblob** [bmbrands/theme_bootstrap#387]
When a group is defined the items are tending to overlap. Here's an example from the Assignment settings page...

Clean theme:
![screen shot 2015-09-11 at 10 44 01](https://cloud.githubusercontent.com/assets/664139/9811995/54e3cba4-5872-11e5-8adb-3337b47e72fe.png)

Bootstrap:
![screen shot 2015-09-11 at 10 43 34](https://cloud.githubusercontent.com/assets/664139/9811999/5c251bde-5872-11e5-934f-de30e1190481.png)

**Comment by thepurpleblob** [comment]
I think it's this...

.mform .iconhelp {
    margin-right: -16px;
    margin-left: 4px;
}

the -16px right margin seems spurious. It causes this problem and stops the form labels lining up (in the same way that do in the clean theme anyway)

**Comment by bmbrands** [comment]
Thanks For the report!! All fixed and closing this issue
