### ISSUE TITLE
the bullets in bullet points do not show due to 0 margin

### ISSUE THREAD

**Issue by thepurpleblob** [bmbrands/theme_bootstrap#388]
To reproduce, create a page and add a bullet pointed list as the content. Save and display.

No bullets are show.

Bootstrap theme:
![screen shot 2015-09-15 at 14 07 19](https://cloud.githubusercontent.com/assets/664139/9877181/21f36e9a-5bb3-11e5-9468-85b07f889a02.png)

Clean theme:
![screen shot 2015-09-15 at 14 08 08](https://cloud.githubusercontent.com/assets/664139/9877241/90cfbe54-5bb3-11e5-9287-a4384f234d50.png)

The clean theme has the following css for ul and ol...
ul, ol {
    padding: 0;
    margin: 0 0 10px 25px;
}

The 25px left-margin makes all the difference and it seems to be absent from Bootstrap

**Comment by bmbrands** [comment]
I know about this issue. And have been adding margins to uls and ols in child themes. I have implemented your suggested fixed and I hope this will not cause any other issues :). Lots of Moodle content / course formats etc use ul for listing sections, modules and lots more...
So fingers crossed and thanks for reporting this!
