### ISSUE TITLE
Activity/Resource edit box corrupted in hidden sections

### ISSUE THREAD

**Issue by thepurpleblob** [bmbrands/theme_bootstrap#389]
Firstly, I have not been able to reproduce this problem but we have quite a number of instances in different courses. This only appears in sections that have been hidden. It's all fine in core themes (e.g. Clean).  I'm struggling to see what might be going wrong...

Anyway, the list of options in the pop-up box has become mis-aligned. Worse, the bottom few (e.g. delete) are no longer selectable at all. Unhiding the topic 'fixes' it. 
![screen shot 2015-09-23 at 10 53 50](https://cloud.githubusercontent.com/assets/664139/10042257/368d4b3e-61e2-11e5-97b6-5a0d56c764ce.png)
Thoughts?

**Comment by gjb2048** [comment]
The section underneath is where the icons are coming from.  That is styled by the 'right' class and looks like a z-index issue from somewhere.  I don't recall core course format styles being that way.  Check contributed ones / investigate that area when editing is on.

**Comment by gjb2048** [comment]
P.s. hide the section below looks like how to replicate.

**Comment by bmbrands** [comment]
Thanks for reporting this. The z-indexing issue does not occur with the clean theme. Not being able to select the last item in the dropdown happens on both the clean theme and the bootstrap theme. Will try if I can find a fix.

**Comment by thepurpleblob** [comment]
Just to add to this... it's show its head only on longer, hidden topics. The first few resources/activities generally work fine - only the ones a bit further down start to degrade.

**Comment by mackensen** [comment]
We're seeing this as well in 3.1

**Comment by bmbrands** [comment]
closing since fixed
