### ISSUE TITLE
Seems to be an issue with changing the background color and image.

### ISSUE THREAD

**Issue by ChristiaanGrobler** [bmbrands/theme_bootstrap#396]
Hi, I'm using the latest bootstrap and Moodle versions.

I'm having trouble changing the background color or images via Appearance > Themes > More 

![backgroundissue](https://cloud.githubusercontent.com/assets/15375030/10811738/efff346e-7e17-11e5-93e8-97894349791d.png)

After changing a few colors or adding a background then selecting "Save Changes" nothing happens.

Am I missing something?

Anyone's help will be much appreciated.

**Comment by bmbrands** [comment]
Hi Christiaan. The theme more is a theme on its own and not this bootstrap theme. If you want to see the colours configured for theme More you should select theme More from the theme selector.
