### ISSUE TITLE
Create BS4 development branch

### ISSUE THREAD

**Issue by gjb2048** [bmbrands/theme_bootstrap#413]
Hi Bas,

What about a BS4 development branch pulled from: https://github.com/iamandrew/theme_bootstrap/tree/bootstrap4 ?

Cheers,

Gareth

**Comment by bmbrands** [comment]
Yes would be a good idea. Or maybe just Andrew to be a collaborator on this repo so he can push it here and have all the credit for his work

**Comment by gjb2048** [comment]
Thinking without knowing, is it possible to create a 'bootstrap4_dev' branch then Andrew makes a pull request (push) on that instead of 'master' then he'd get credit?  Or.... with a local repo, have his repo in the list of remotes then create the 'bootstrap4_dev' on your repo and cherry pick the commits from his: https://github.com/iamandrew/theme_bootstrap/commits/bootstrap4 ?

**Comment by gjb2048** [comment]
Or... if BS4 is the future, branch now with the bootstrap3_master and 'master' be upgraded to BS4 with a pull (push) from his repo.

**Comment by iamandrew** [comment]
I'm happy to go with whatever option works for this.
It would be good to get the work merged in to this repo as soon as possible so we can get more eyes looking and hands coding on it, especially so we can get ahead for https://moodle.org/mod/forum/discuss.php?d=334523

**Comment by iamandrew** [comment]
bootstrap4 branch now added.

**Comment by bmbrands** [comment]
Cool! Thanks Andrew
