### ISSUE TITLE
MOODLE_30_STABLE has unresolved merge issue

### ISSUE THREAD

**Issue by pavelsokolov** [bmbrands/theme_bootstrap#414]
See line 31 of version.php:

Parse error: syntax error, unexpected '<<' (T_SL) in /var/www/ilearn2dev/theme/bootstrap/version.php on line 31

**Comment by bmbrands** [comment]
Oops thanks for notifying me. I have fixed the issue so please pull the latest version from GitHub

**Comment by gjb2048** [comment]
Aside and 'interesting', plus I did not notice but watching anyway, TravisCI picked this up: https://travis-ci.org/bmbrands/theme_bootstrap/builds/124966909
