### ISSUE TITLE
Issue with collapsible menu

### ISSUE THREAD

**Issue by jrm-unamur** [bmbrands/theme_bootstrap#420]
Hi Bas
With new 3.1 release or Moodle and last upgrade of bootstrap theme (build number 2016042200) I'm experiencing problems with collapsible menus in menu bar in some contexts.
For example, such menus do not open on click on "notifications page" and other admin pages, and language menu has disappeared from the menu bar (lang menu set to yes in administration).
I noticed this behaviour not only on my child theme of course, but also in other themes based on your bootstrap3 implementation (flexibase, elegance) as well as with bootstrap them itself.
It appears that in these contexts the "open" css class is not toggled in the li.dropdown element on click.
I can't figure out why, any ideas?

Kind regards

Jean-Roch Meurisse

**Comment by jrm-unamur** [comment]
Adding 
$(document).ready(function() {
                    $(".dropdown-toggle").dropdown();
                });
in a theme .js module fixes the issue, but it may no be the best solution...
Best

Jean-Roch

**Comment by bmbrands** [comment]
Okay that's very weird! Is your site available from the internet so I can have a look?

**Comment by jrm-unamur** [comment]
Unfortunately it's not in production yet!
The fix is working, but in pages where there was no problems, I now have a js error in console
first.js:31218 Uncaught TypeError: $(...).dropdown is not a function
Having a look at the generated page, I noticed that there are differences in js loading:
In pages where dropdown is not working I have
require(['core/first'], function() {
;
require(['jquery', 'theme_bootstrapbase/bootstrap'], function($) {
    // Setup closing of bootstrap alerts.
    $().alert();
});
;
and not in "working" pages.
This loading is weird since your theme has no dependency against bootstrapbase...

**Comment by jrm-unamur** [comment]
Found it ! Core moodle templates for notifications now (since 3.1) load theme_bootstrapbas/bootstrap to handle close buttons... (they should not have done that I think)
These templates (4 of them) must be overridden in custom coez themes to avoid this loading themes
Now dropdowns are working everywhere :-)

**Comment by lazydaisy** [comment]
This was talked about in the Moodle Tracker at the time.
There was / is tracker to reverse some aspect of these changes.
I'll try and find the tracker issue number.

**Comment by lazydaisy** [comment]
Here is a link to the tracker where all these changes were made.
https://tracker.moodle.org/browse/MDL-30811

This next link is a comment by John Oakly in that tracker issue talking about the close button.
https://tracker.moodle.org/browse/MDL-30811?focusedCommentId=398026&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-398026

**Comment by bmbrands** [comment]
Ah okay. So in that case there should be a way to replicate this issue. @jrm-unamur could you give me an example of a page where the issue exists? Also need to figure out how to override these templates in the bootstrap theme. So if you have an example of that, that would be great.

And thanks @lazydaisy for pointing out the problem.

It worries me to see more core code locking into the bootstrapbase theme which is going to be stuck at Bootstrap 2 forever it seems.

**Comment by gjb2048** [comment]
Themes forum ref: https://moodle.org/mod/forum/discuss.php?d=334245

**Comment by gjb2048** [comment]
I'm seriously worried that Moodle will date-itself by sticking with BS2 and making it harder for other frameworks to exist.  This is a Dinosaur moment.

**Comment by jrm-unamur** [comment]
Dear @bmbrands 
An example is the notifications page (admin/index.php).
Overriding these templates is not difficult. 
You just need to add a templates/core directory within the bootstrap theme dir and add the 4 files
notification_error.mustache
notification_info.mustache
notification_success.mustache
notification_warning.mustache
In each file, delete the js inclusion of theme_bootstrapbase/bootstrap and adapt css classes if necessary

**Comment by gjb2048** [comment]
Oh so helpful: https://docs.moodle.org/dev/Templates#How_to_I_override_a_template_in_my_theme.3F

**Comment by jobyh** [comment]
@jrm-unamur is correct should just be a case of adding a `templates/core/notification_<level>.mustache` for each of the notifications into the theme and clearing the cache. Including theme JavaScript via non-theme core seems crazy to me.

I suspect I can reason why they've done it but seems like a real mess. Perhaps I'm missing something clever.

**Comment by gjb2048** [comment]
Looks like the had to extend the word 'clever' to include the 'base' theme: https://github.com/moodle/moodle/tree/MOODLE_31_STABLE/theme/base/templates/core thus adding globally only to remove somewhere else.

**Comment by jobyh** [comment]
@gjb2048 ha! Nice spot ... why not just add that JS include in an overriden template in the bootstrapbase theme then I wonder? All seems rather back-to-front...

**Comment by bmbrands** [comment]
Ah Thanks everyone! I get it now. Will work on overridden templates for Bootstrap 3 soon.

**Comment by gjb2048** [comment]
More like ass over tit.

**Comment by bmbrands** [comment]
Okay now fixed by adding the core templates in the bootstrap theme. Thanks everybody for helping find and fix this issue!

**Comment by lazydaisy** [comment]
Well done Bas!
