### ISSUE TITLE
Config.php references Elegance for less call back

### ISSUE THREAD

**Issue by roelmann** [bmbrands/theme_bootstrap#428]
https://github.com/bmbrands/theme_bootstrap/blob/master/config.php#L53-54
$THEME->lessvariablescallback = 'theme_elegance_less_variables';
$THEME->extralesscallback = 'theme_elegance_extra_less';
The lessvariablescallback and the extralesscallback need to be brought internally within the theme (if used) as Elegance is not a requirement for installing bootstrap as a theme.

**Comment by bmbrands** [comment]
Your right Richard. That's a bit of a mess. Cleaned it up now an thanks for reporting!
