### ISSUE TITLE
Versioning

### ISSUE THREAD

**Issue by mackensen** [bmbrands/theme_bootstrap#433]
This is more a question than anything. I'm updating my child theme for 3.1. Should I be developing against `master`, `MOODLE_31_BETA`, or something else altogether? Master's version is older than MOODLE_31_BETA, but MOODLE_31_BETA is missing certain fixes such as #388. Another major difference is that MOODLE_31_BETA has a bunch of new gradients, and master doesn't. We prefer a flat affect in our child theme so we were going to take those out, but they're not present in master already so if that's the future of the release we'll just develop against that. Thanks for any insight.

**Comment by bmbrands** [comment]
If you're developing a child BS theme for 3.1. it would be best to use the MOODLE_31_BETA branch. 

In the next few weeks I have scheduled time to work towards a stable release and will work on issues reported here and the ones I can find myself.

The gradient were just for testing only. I agree they are not great when creating child themes and the aim for this theme is to be used as a parent theme primarily. In fact. I'll remove them again today :)

If you find any issues while developing do not hesitate to post them here!

**Comment by mackensen** [comment]
Great, thanks @bmbrands :)
