### ISSUE TITLE
user_menu & custom_menu broken (depending on page) 

### ISSUE THREAD

**Issue by mike-wilson-uk** [bmbrands/theme_bootstrap#434]
Hi there, I use bootstrap as the parent for my child theme. I've run into a problem with the user_menu and custom_menu in that the menus don't display on different pages.

If I visit the following page, top level menu buttons appears, but the menu doesn't animate when the button is pressed:

moodle/admin/index.php?cache=1

If I visit this page the menus work as expected:
moodle/course/management.php

It's a strange problem. I initially thought it was a problem with a layout file but both pages use default.php.

I've had a look through the Developer tools Console in Chrome but can't find much that looks out of place.

MOODLE_31_BETA branch
Moodle 3.1+ (Build: 20160603) 
Chrome (Version 51.0.2704.84 (64-bit)).

Hope you can help,

Cheers

**Comment by davidscotson** [comment]
Is this possibly the same things as #420 and #429?

**Comment by mike-wilson-uk** [comment]
Hi David, yep those seem like the same issue. Sounds like Bas is on the case. Think I'll have a play too now I've got a bit of background to the issue.

Cheers

**Comment by bmbrands** [comment]
Yes looks like the same issue. I am currently working on some project deadlines but hope to find some time for this theme again soon.

**Comment by bmbrands** [comment]
Should now be fixed!

**Comment by mike-wilson-uk** [comment]
Worked a treat. Thanks for the quick response, much appreciated :)
