### ISSUE TITLE
No styling on autocomplete forms

### ISSUE THREAD

**Issue by mackensen** [bmbrands/theme_bootstrap#435]
There's no styling on the drop-down from the autocomplete forms. See for example this screenshot from the new course meta link interface.
![autocomplete no styling](https://cloud.githubusercontent.com/assets/553370/16954660/a95e0640-4d9f-11e6-9b8f-fbb9a7bdd25c.png)

Compare a similar site in Clean:
![autocomplete styling](https://cloud.githubusercontent.com/assets/553370/16954803/44cfada4-4da0-11e6-88b6-25f4881d57f3.png)

**Comment by bmbrands** [comment]
Thanks for reporting this. I hope to find time to work on the theme soon.

**Comment by mackensen** [comment]
I took a stab at this; see #436.

**Comment by bmbrands** [comment]
Closing because you fixed it!!! Cool stuff.
