### ISSUE TITLE
Bootstrap JS need updated to v3.3.7 for Moodle 3.2

### ISSUE THREAD

**Issue by davidscotson** [bmbrands/theme_bootstrap#452]
If you have a version of Bootstrap JS before 3.3.7 then it does a version check on JQuery and fails to load on Moodle 3.2 because it has updated JQuery to version 3. The changes to support it are fairly minor.

**Comment by gjb2048** [comment]
Hi @davidscotson and @bmbrands,

Feel free to poach from: https://github.com/gjb2048/moodle-theme_shoehorn/tree/master/amd - if I get a mo I'll do the patch.

G

**Comment by bmbrands** [comment]
I have updated bootstrap to version 3.3.7 and stole @gjb2048's bootstrap.js and Gruntfile stuff. Thanks for reporting this!
