### ISSUE TITLE
Fatal error: Access level to theme_bootstrap_core_files_renderer::

### ISSUE THREAD

**Issue by arnold79** [bmbrands/theme_bootstrap#459]
I was successfully upgraded from 2.8 to 3.3. But later i found an error on some link that says :"Fatal error: Access level to theme_bootstrap_core_files_renderer::fm_print_generallayout() must be protected (as in class core_files_renderer) or weaker in /xxx/xxx/xxx/moodle/theme/bootstrap/renderers/files_renderer.php on line 29"
Is there any solution? Tks

**Comment by bmbrands** [comment]
That's weird? That renderer should no longer be used. What version of bootstrap are you using?

**Comment by arnold79** [comment]
Version 2014120803
Where should i download the update? And how to update it. Tks a lot.

**Comment by bmbrands** [comment]
You can download a zip file from the master branch here on github. That should do it

**Comment by arnold79** [comment]
Its work now.
Tks
